# Pipeline for å publisere 11ty-blogg til webhotell

trigger:
- main


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh_optkontek'
    sourceFolder: '_site'
    contents: '**'
    targetFolder: '/www/blogg'
    readyTimeout: '20000'

